# Code generated by the Rhombus AI Builder for the final "Custom" node (orders_cleaned).
# Taken from the node's Edit Code panel on 2026-10-05; comments trimmed and the two date
# format attempts folded into a loop for readability. Logic is unchanged.
import re

df = input_df_1.copy()
output_mask = pd.DataFrame(False, index=df.index, columns=df.columns)

# --- 1. COUNTRY ---
country_mapping = {
    'au': 'Australia', 'aus': 'Australia', 'australia': 'Australia',
    'us': 'United States', 'usa': 'United States', 'united states': 'United States',
    'united states of america': 'United States',
    'in': 'India', 'ind': 'India', 'india': 'India',
    'uk': 'United Kingdom', 'gbr': 'United Kingdom', 'united kingdom': 'United Kingdom',
    'great britain': 'United Kingdom',
    'sg': 'Singapore', 'sgp': 'Singapore', 'singapore': 'Singapore',
}
def clean_country(val):
    if pd.isna(val):
        return val
    return country_mapping.get(str(val).strip().lower(), val)
country_original = df['country'].copy()
df['country'] = df['country'].apply(clean_country)
output_mask['country'] = df['country'] != country_original

# --- 2. STATUS ---
status_original = df['status'].copy()
df['status'] = df['status'].replace('canceled', 'cancelled')
output_mask['status'] = df['status'] != status_original

# --- 3. AMOUNT_USD ---
def clean_amount_usd(val):
    if pd.isna(val):
        return np.nan
    val_str = str(val).strip().lstrip('$').replace(',', '')
    try:
        return float(val_str)
    except Exception:
        return np.nan
amount_original = df['amount_usd'].copy()
df['amount_usd'] = df['amount_usd'].apply(clean_amount_usd)
output_mask['amount_usd'] = df['amount_usd'] != amount_original

# --- 4. QUANTITY ---
def clean_quantity(val):
    if pd.isna(val):
        return np.nan
    try:
        val_float = float(val)
        return int(val_float) if val_float == int(val_float) else np.nan
    except Exception:
        return np.nan
quantity_original = df['quantity'].copy()
df['quantity'] = df['quantity'].apply(clean_quantity)
output_mask['quantity'] = df['quantity'] != quantity_original
rows_to_drop = (df['quantity'].isna()) | (df['quantity'] < 0)
df = df[~rows_to_drop].reset_index(drop=True)
output_mask = output_mask[~rows_to_drop].reset_index(drop=True)

# --- 5. EMAIL ---
email_pattern = r'^[^@\s]+@[^@\s]+\.[^@\s]+$'
def clean_email(val):
    if pd.isna(val):
        return ''
    val_str = str(val).strip()
    return val_str if re.match(email_pattern, val_str) else ''
email_original = df['email'].copy()
df['email'] = df['email'].apply(clean_email)
output_mask['email'] = df['email'] != email_original

# --- 6. ORDER_DATE ---
def clean_order_date(val):
    if pd.isna(val):
        return np.nan
    if isinstance(val, pd.Timestamp):
        return val.strftime('%Y-%m-%d')
    val_str = str(val).strip()
    for fmt in ('%Y-%m-%d', '%m/%d/%Y'):
        try:
            return pd.to_datetime(val_str, format=fmt).strftime('%Y-%m-%d')
        except Exception:
            pass
    return np.nan
order_date_original = df['order_date'].copy()
df['order_date'] = df['order_date'].apply(clean_order_date)
output_mask['order_date'] = df['order_date'] != order_date_original

output_df = df
output_mask = output_mask.astype(bool)
